// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PiecesController from "./pieces_controller"
application.register("pieces", PiecesController)

import SheetVisualizerController from "./sheet_visualizer_controller"
application.register("sheet-visualizer", SheetVisualizerController)
