// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LabelModalController from "./label_modal_controller"
application.register("label-modal", LabelModalController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PiecesController from "./pieces_controller"
application.register("pieces", PiecesController)

import ResizablePanelController from "./resizable_panel_controller"
application.register("resizable-panel", ResizablePanelController)

import SheetVisualizerController from "./sheet_visualizer_controller"
application.register("sheet-visualizer", SheetVisualizerController)

import ReportIssueController from "./report_issue_controller"
application.register("report-issue", ReportIssueController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)
